/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GST_API_VERSION "1.0"

#define GST_LICENSE "LGPL"

#define GST_PACKAGE_NAME "GStreamer gz decoder"

#define GST_PACKAGE_ORIGIN "cassianokleinert@gmail.com"

#define PACKAGE "gzdec"

#define PACKAGE_VERSION "1.19.0.1"

